apiVersion: v1
kind: Service
metadata:
  name: akhq
  namespace: kafka
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: akhq

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: akhq
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akhq
  template:
    metadata:
      labels:
        app: akhq
    spec:
      containers:
        - name: akhq
          image: tchiotludo/akhq:latest
          ports:
            - containerPort: 8080
          env:
            - name: AKHQ_CONFIGURATION
              value: |
                akhq:
                  connections:
                    my-cluster:
                      properties:
                        bootstrap.servers: "my-cluster-kafka-bootstrap.kafka:9092"

